package com.salpiras.citizendocs.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Generated with Material Theme Builder. The medium/high-contrast variants the tool also
// emits were dropped: nothing referenced them, and unused schemes drift out of date.

internal val primaryLight = Color(0xFF30628C)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFCEE5FF)
internal val onPrimaryContainerLight = Color(0xFF001D33)
internal val secondaryLight = Color(0xFF625690)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFE7DEFF)
internal val onSecondaryContainerLight = Color(0xFF1E1048)
internal val tertiaryLight = Color(0xFF1F6A4E)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFA8F2CE)
internal val onTertiaryContainerLight = Color(0xFF002114)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFF7F9FF)
internal val onBackgroundLight = Color(0xFF181C20)
internal val surfaceLight = Color(0xFFF7F9FF)
internal val onSurfaceLight = Color(0xFF181C20)
internal val surfaceVariantLight = Color(0xFFDEE3EB)
internal val onSurfaceVariantLight = Color(0xFF42474E)
internal val outlineLight = Color(0xFF72777F)
internal val outlineVariantLight = Color(0xFFC2C7CF)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2D3135)
internal val inverseOnSurfaceLight = Color(0xFFEFF1F6)
internal val inversePrimaryLight = Color(0xFF9CCBFB)
internal val surfaceDimLight = Color(0xFFD8DAE0)
internal val surfaceBrightLight = Color(0xFFF7F9FF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF1F3F9)
internal val surfaceContainerLight = Color(0xFFECEEF4)
internal val surfaceContainerHighLight = Color(0xFFE6E8EE)
internal val surfaceContainerHighestLight = Color(0xFFE0E2E8)

internal val primaryDark = Color(0xFF9CCBFB)
internal val onPrimaryDark = Color(0xFF003354)
internal val primaryContainerDark = Color(0xFF104A73)
internal val onPrimaryContainerDark = Color(0xFFCEE5FF)
internal val secondaryDark = Color(0xFFCCBEFF)
internal val onSecondaryDark = Color(0xFF33275E)
internal val secondaryContainerDark = Color(0xFF4A3E76)
internal val onSecondaryContainerDark = Color(0xFFE7DEFF)
internal val tertiaryDark = Color(0xFF8DD5B3)
internal val onTertiaryDark = Color(0xFF003826)
internal val tertiaryContainerDark = Color(0xFF005138)
internal val onTertiaryContainerDark = Color(0xFFA8F2CE)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF101418)
internal val onBackgroundDark = Color(0xFFE0E2E8)
internal val surfaceDark = Color(0xFF101418)
internal val onSurfaceDark = Color(0xFFE0E2E8)
internal val surfaceVariantDark = Color(0xFF42474E)
internal val onSurfaceVariantDark = Color(0xFFC2C7CF)
internal val outlineDark = Color(0xFF8C9199)
internal val outlineVariantDark = Color(0xFF42474E)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE0E2E8)
internal val inverseOnSurfaceDark = Color(0xFF2D3135)
internal val inversePrimaryDark = Color(0xFF30628C)
internal val surfaceDimDark = Color(0xFF101418)
internal val surfaceBrightDark = Color(0xFF36393E)
internal val surfaceContainerLowestDark = Color(0xFF0B0E12)
internal val surfaceContainerLowDark = Color(0xFF181C20)
internal val surfaceContainerDark = Color(0xFF1C2024)
internal val surfaceContainerHighDark = Color(0xFF272A2F)
internal val surfaceContainerHighestDark = Color(0xFF323539)
